### ISSUE TITLE
Please help close a duplicate PR for sn-operator

### ISSUE THREAD

**Issue by ericsyh** [redhat-openshift-ecosystem/certified-operators#3061]
Hi team,

I am pushing the PR https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3058 for the sn-operator certificate but the CI logs tell me that there is a duplicate PR https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2806 and refuse to test my PR.

```
[submission-validation : submission-validation] 2023-11-03 14:32:55,335 [operator-cert] DEBUG GET GitHub request url: https://api.github.com/repos/redhat-openshift-ecosystem/certified-operators/pulls
[submission-validation : submission-validation] 2023-11-03 14:32:55,335 [operator-cert] DEBUG GET GitHub request params: None
[submission-validation : submission-validation] 2023-11-03 14:32:56,232 [operator-cert] ERROR There is more than one pull request for the Operator Bundle sn-operator
[submission-validation : submission-validation] 2023-11-03 14:32:56,232 [operator-cert] ERROR DUPLICATE: operator sn-operator (0.2.1-rc): https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2806
[submission-validation : submission-validation] Traceback (most recent call last):
[submission-validation : submission-validation]   File "/home/user/.venv/bin/verify-pr-uniqueness", line 8, in <module>
[submission-validation : submission-validation]     sys.exit(main())
[submission-validation : submission-validation]              ^^^^^^
[submission-validation : submission-validation]   File "/home/user/.venv/lib/python3.11/site-packages/operatorcert/entrypoints/verify_pr_uniqueness.py", line 51, in main
[submission-validation : submission-validation]     verify_pr_uniqueness(repos, args.pr_url, args.bundle_name)
[submission-validation : submission-validation]   File "/home/user/.venv/lib/python3.11/site-packages/operatorcert/__init__.py", line 399, in verify_pr_uniqueness
[submission-validation : submission-validation]     raise RuntimeError("Multiple pull requests for one Operator Bundle")
[submission-validation : submission-validation] RuntimeError: Multiple pull requests for one Operator Bundle
```

But the PR 2806 author account is disabled. Could you help close that PR and unblock my PR 3058? Thanks a lot.

**Comment by ericsyh** [comment]
cc @jinhli @jsm84 @jfrancin @kpouget appreciate a lot if any of you have the permission to close the duplicate PR https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2806

**Comment by jfrancin** [comment]
That PR is now closed.

**Comment by jfrancin** [comment]
I've re-triggered your newer PR, #3058.

**Comment by ericsyh** [comment]
Many thanks! @jfrancin
