### ISSUE TITLE
RuntimeError: Annotations file not found

### ISSUE THREAD

**Issue by tahmmee** [redhat-openshift-ecosystem/certified-operators#649]
Hi, I'm trying to go through the certification steps described here.  One of the errors I'm seeing is the following, and I'm not sure the cause:
```
[get-supported-versions : supported-version-check] ++ cat config.yaml
[get-supported-versions : supported-version-check] ++ yq -r .organization
[get-supported-versions : supported-version-check] + ORGANIZATION=certified-operators
[get-supported-versions : supported-version-check] ++ ocp-version-info operators/couchbase-enterprise-certified certified-operators
[get-supported-versions : supported-version-check] Traceback (most recent call last):
[get-supported-versions : supported-version-check]   File "/usr/local/bin/ocp-version-info", line 33, in <module>
[get-supported-versions : supported-version-check]     sys.exit(load_entry_point('operatorcert==1.0.0', 'console_scripts', 'ocp-version-info')())
[get-supported-versions : supported-version-check]   File "/usr/local/lib/python3.9/site-packages/operatorcert/entrypoints/ocp_version_info.py", line 41, in main
[get-supported-versions : supported-version-check]     version_info = ocp_version_info(bundle_path, args.pyxis_url, args.organization)
[get-supported-versions : supported-version-check]   File "/usr/local/lib/python3.9/site-packages/operatorcert/__init__.py", line 142, in ocp_version_info
[get-supported-versions : supported-version-check]     bundle_annotations = get_bundle_annotations(bundle_path)
[get-supported-versions : supported-version-check]   File "/usr/local/lib/python3.9/site-packages/operatorcert/__init__.py", line 43, in get_bundle_annotations
[get-supported-versions : supported-version-check]     raise RuntimeError("Annotations file not found")
[get-supported-versions : supported-version-check] RuntimeError: Annotations file not found
[get-supported-versions : supported-version-check] + VERSION_INFO=
```

Is this an annotation file that I'm supposed to add somewhere?

**Comment by tahmmee** [comment]
managed to resolve this by virtue of being a g
